name: mongo_pool
description: A MongoDB connection pool for Dart. Using this package, your application will open as many database connections as you specify as soon as it runs.

version: 1.4.1
homepage: https://github.com/merterkoc/mongo_pool

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_annotation: ^1.6.0
  meta: ^1.9.1
  mongo_dart: ^0.10.0
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  build_runner: ^2.4.7
  cached: ^1.6.3
  lints: ^2.0.0
  test: ^1.16.0
