name: mongo_pool
description: A MongoDB connection pool for Dart. Using this package, your application will open as many database connections as you specify as soon as it runs. You can
  open, close and change the number of these links at any time.

version: 1.0.1
homepage: https://github.com/merterkoc/mongo_pool

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  mongo_dart: ^0.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
