name: mongo_pool
description: A MongoDB connection pool for Dart. Using this package, your application will open as many database connections as you specify as soon as it runs.

version: 1.0.3
homepage: https://github.com/merterkoc/mongo_pool

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  mongo_dart: ^0.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
